import './global.css';

export const metadata = {
  title: "Javier Villalba",
  description: "LinkTree Generated by NextJS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
